import Navbar from "@/components/Navbar/Navbar"
import "./globals.css"
import type { Metadata } from "next"
import {Roboto} from "next/font/google"


const roboto = Roboto({
  subsets: ["latin"],
  display: "swap",
  weight: ["300", "400", "500", "700"],
})


export const metadata: Metadata = {
	title: "Rami Elbatnigi",
	description: "Generated by create next app",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html>
			<body className="flex flex-col">
				<Navbar />
				{children}
			</body>
		</html>
	)
}
